language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_97726d3378bf_key -iv $encrypted_97726d3378bf_iv
  -in keys.xml.enc -out ./app/src/main/res/values/keys.xml -d
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- "./gradlew clean build"
notifications:
  slack: mash-up-kr:knArKlSf68S6YuPOJpBnEq1z
